### ISSUE TITLE
still the best option?

### ISSUE THREAD

**Issue by jamesdixon** [asgerf/dartify#1]
Hey @asgerf! 

I realize this repo is pretty old but I came across it in my search for an alternative to Fabric.js on the Flutter side. We currently use Fabric.js on our mobile app (Ionic) and web app, but are currently redoing our app in Flutter. 

Curious if there are other, better projects, that might be used to convert Fabric to Dart.

**Comment by asgerf** [comment]
Hi @jamesdixon.

This project is a discontinued experiment, and I'd avoid using it entirely.

I believe the official way of doing this is https://github.com/dart-lang/js_facade_gen.

**Comment by jamesdixon** [comment]
Thank you, @asgerf! Just curious: assuming this was still a relevant project, would the Fabric.dart library created be able to be consumed in Flutter? Not clear to me if this library or `js_facade_gen` are web-only.

**Comment by asgerf** [comment]
Since Fabric is an HTML canvas library you'd probably have to run it in a web view, but tbh I don't know. You'd have to ask somewhere else.
